### PR TITLE
fix few things. still need to fix more. TML please fix the name of function 

### PR DESCRIPTION
**Pull request by 4solo**

### CODE REVIEW

**Comment by AdrianFeng** [comment]
I have already use the name in user/service and I think it is fine otherwise I have to change as well or if you guys insist on that....

**Comment by AdrianFeng** [comment]
why you check failed...

**Comment by 4solo** [comment]
ok. never mind

**Comment by Red-C** [comment]
it is easy to fix them all in ide. I will fix them later.

**Pull request closed without merging**
